bookSearch/urls.py
from django.urls import path
from . import views

app_name = "bookSearch"

urlpatterns = [
	path('', views.index, name = 'index'),
    path('book-data/', views.bookData, name = 'book_data')
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookSearch.urls'))
]

bookSearch/models.py
from django.db import models

# Create your models here.

class Book (models.Model):
    id = models.CharField(max_length = 200, primary_key = True)
    title = models.CharField(max_length = 200)
    thumbnail = models.CharField(max_length = 100)
    author = models.CharField(max_length = 100, blank = True)
    description = models.CharField(max_length = 200)

bookSearch/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json, requests
from .models import Book
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@csrf_exempt

def index(request):
    return render(request, 'index.html')

def bookData(request):
    try:
        q = request.GET['q']
    except:
        q = 'Not Found'

    response = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + q).json()

    return JsonResponse(response)

bookSearch/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        Book Search
    </title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        const url_book_data = "{% url 'bookSearch:book_data' %}?q=";
    </script>


</head>
<body>

    <div class="content">
        <div class="container">
            <div class="row align-items-center">
                <div class="col">
                    <h1>Book Search</h1>
                    <hr>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row align-items-center">
            <span>
                <input class="form-control" type="text" placeholder="Insert book title here" id="keyword">
            </span>
            <span>
                <button class="btn btn-success" type="button" id="act" >Search</button>
            </span>
        </div>
    </div>

    <br>
    <div class="container">
        <ol id="hasil"></ol>
    </div>




    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> -->
    
</body>
</html>